#!/bin/bash
#Check if script was ru as root. Exit if false
if [$uid -ne 0]
then 
echo "Please run this script with sudo."
exit
fi
#Define Variables
output=$HOME/research3/sys_info.txt
ip=$(ip addr | inet | tail -2 | head -1)
suids=$(find / -type -perm /4000 2> /dev/null)

#check for researh directory. Creat it if needed
if [ ! -d $HOME/research3 ]
then
mkdir $HOME/research3
fi
#check for output file. clear it if needed. 
if [ -f $output ]
then
   rm $output
fi
echo "A Quick System Audit Script" >> $output

date >> $output
echo " " >> output
echo "Machine Type Info:" >> $output
echo -e "SMACHTYPE \N" >> $output
echo -e "Uname info: $(uname -a) \n" >> $output
echo -e "IP Info:" >> $output
echo -e "$ip \n" >> $output
echo -e "Hostname: $(hostname -s) \n" >> output
echo "DNS Servers: " >> $output
cat /etc/resolv.conf >> $output
echo -e "\nMemory Info:" >> $output
free >> $output
echo -e "\ncpu Info:" >> $output
lscpu | grep CPU >> $output
echo -e "\nDisk Usage:" >> $output
df -H |  head -2 >> $ output
echo -e "\NWho is Logged in: n\ $(who -a) \n" >> $output
exho -e "\nSUID Files:" >> $output 
echo $suid >> $output
echo -e "\nTop 10 Processes" >> $output
ps aux --sort -%mem |awk {'print $1, $2, $3, $4, $11'} | head >> $output

